project:
  type: website
  output-dir: docs

website:
  title: "MADA Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects  
    right:
      - icon: github
        href: https://github.com/alex8528/mada-portfolio

format:
  html:
    theme: cosmo
    toc: true
