project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "presentation-exercise/presentation-exercise.qmd"
    - "data-exercise/data-exercise.qmd"
    - "cdcdata-exercise/cdcdata-exercise.qmd"
    - "class-project/index.qmd"
    - "!alextejadastrop-ready-exercise/products/**"


website:
  title: "MADA Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: presentation-exercise/presentation-exercise.qmd
        text: Presentation Exercise
      - href: about.qmd
        text: About Me
      - href: class-project/index.qmd
        text: Class Individual Project
      - href: starter-analysis-exercise.qmd
        text: Starter Analysis Exercise
      - href: contacts.qmd
        text: Contact / Links
    right:
      - icon: github
        href: https://github.com/alex8528/mada-portfolio

format:
  html:
    theme: cosmo
    toc: true
